"""Kommun/län register lookup (task A-01).

Data comes from the bundled ``data/kommun_register.json``, generated by
``tools/refresh_kommun_register.py`` from SCB's own region metadata —
never hand-maintained.

Name matching is deliberately conservative: exact normalized match, a
small set of documented transformations (drop " kommun"/" stad"
suffixes, genitive trailing "s"), and one irregular-genitive map. A name
we cannot confidently match returns ``None`` — a missing code is
acceptable, a wrong one is not.
"""

from __future__ import annotations

import json
import re
from functools import cache
from importlib import resources

_SUFFIXES = (" kommun", " stad", " municipality", "s kommun", "s stad")

#: Irregular genitives where stripping a trailing "s" is not enough.
#: Kept deliberately tiny and explicit — additions require verification
#: against the register, not guesswork.
_IRREGULAR = {
    "falu": "falun",
}

_WHITESPACE = re.compile(r"\s+")


class KommunRegister:
    def __init__(self, municipalities: dict[str, str], counties: dict[str, str]) -> None:
        self._municipalities = municipalities
        self._counties = counties
        self._by_name = {_normalize(name): code for code, name in municipalities.items()}

    @property
    def municipality_count(self) -> int:
        return len(self._municipalities)

    def municipality_name(self, code: str) -> str | None:
        return self._municipalities.get(code)

    def county_name(self, county_code: str) -> str | None:
        return self._counties.get(county_code)

    def county_code_for(self, municipality_code: str) -> str | None:
        if municipality_code in self._municipalities:
            return municipality_code[:2]
        return None

    def municipality_code(self, name: str) -> str | None:
        """Resolve a kommun name to its 4-digit code, or None if unsure.

        Tries, in order: exact normalized match; suffix-stripped match
        ("Stockholms kommun", "Göteborgs stad"); irregular-genitive map
        ("Falu kommun" → Falun); genitive trailing-"s" strip ("Stockholms"
        → Stockholm — tried last so genuine s-names like Borås, Västerås
        match exactly first).
        """
        candidate = _normalize(name)
        if not candidate:
            return None
        if candidate in self._by_name:
            return self._by_name[candidate]
        for suffix in _SUFFIXES:
            if candidate.endswith(suffix):
                return self.municipality_code(candidate.removesuffix(suffix))
        if candidate in _IRREGULAR:
            return self._by_name.get(_IRREGULAR[candidate])
        if candidate.endswith("s"):
            return self._by_name.get(candidate[:-1])
        return None


def _normalize(name: str) -> str:
    return _WHITESPACE.sub(" ", name.strip().lower())


@cache
def load_register() -> KommunRegister:
    payload = (
        resources.files("location_intelligence.data")
        .joinpath("kommun_register.json")
        .read_text(encoding="utf-8")
    )
    data = json.loads(payload)
    return KommunRegister(municipalities=data["municipalities"], counties=data["counties"])
