"""Production crawl pipeline: discover -> crawl -> download -> report.

Runs the same stages proven by the smoke test (see brf_scraper.smoke_test),
but against persistent storage and the persistent metadata database instead
of a throwaway temp directory, so results and dedup state accumulate across
runs. This is the backing implementation for `brf-scraper crawl`.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field

from brf_scraper.config import AppSettings
from brf_scraper.crawler.engine import CrawlerEngine
from brf_scraper.crawler.models import CrawlConfig
from brf_scraper.discovery.confidence import ConfidenceBand
from brf_scraper.discovery.engine import DiscoveryEngine
from brf_scraper.discovery.pipeline import DiscoveryPipeline
from brf_scraper.discovery.registry import SqliteVerifiedWebsiteRegistry
from brf_scraper.discovery.search_engine import SearchEngineDiscovery
from brf_scraper.discovery.seed_urls import SeedUrlDiscovery
from brf_scraper.downloader.downloader import Downloader
from brf_scraper.downloader.manager import DownloadManager
from brf_scraper.downloader.models import DownloadRequest, DownloadStatus
from brf_scraper.downloader.sqlite_metadata import SqliteMetadataRepository
from brf_scraper.exceptions import BRFScraperError
from brf_scraper.models.brf import BRF
from brf_scraper.smoke_test import is_likely_annual_report
from brf_scraper.storage.local import LocalStorage
from brf_scraper.utils.logging import get_logger

logger = get_logger(__name__)


@dataclass
class CrawlReport:
    """Report generated by a production crawl run."""

    brf_name: str
    website_url: str | None = None
    discovery_provider: str | None = None

    confidence_band: str | None = None
    confidence_score: float = 0.0
    confidence_explanation: str | None = None
    needs_confirmation: bool = False

    pages_crawled: int = 0
    internal_links: int = 0
    external_links: int = 0

    pdfs_found: int = 0
    annual_reports_detected: int = 0
    downloaded: int = 0
    duplicates: int = 0
    errors: int = 0

    downloaded_files: list[str] = field(default_factory=list)

    execution_time: float = 0.0
    passed: bool = False
    failed_stage: str | None = None
    failed_error: str | None = None


def format_crawl_report(report: CrawlReport) -> str:
    """Format a CrawlReport into a readable text summary.

    Args:
        report: The crawl report.

    Returns:
        Formatted report string.
    """
    lines: list[str] = []

    lines.append("=" * 40)
    lines.append("BRF Crawl Report")
    lines.append("=" * 40)
    lines.append("")
    lines.append(f"BRF: {report.brf_name}")
    lines.append(f"Official website: {report.website_url or 'Not found'}")
    lines.append(f"Discovery provider: {report.discovery_provider or 'N/A'}")
    if report.confidence_band:
        lines.append(
            f"Discovery confidence: {report.confidence_band.upper()} "
            f"({report.confidence_score:.2f})"
        )
        if report.confidence_explanation:
            lines.append(f"  {report.confidence_explanation}")
    if report.needs_confirmation:
        lines.append("")
        lines.append("ACTION REQUIRED: best-guess website needs user confirmation before crawling.")
    lines.append("")
    lines.append(f"Pages crawled: {report.pages_crawled}")
    lines.append(f"Internal links: {report.internal_links}")
    lines.append(f"External links: {report.external_links}")
    lines.append("")
    lines.append(f"PDFs found: {report.pdfs_found}")
    lines.append(f"Annual reports detected: {report.annual_reports_detected}")
    lines.append(f"Downloaded: {report.downloaded}")
    lines.append(f"Duplicates: {report.duplicates}")
    lines.append(f"Errors: {report.errors}")
    lines.append("")

    if report.downloaded_files:
        lines.append("Downloaded files:")
        lines.append("")
        for filename in report.downloaded_files:
            lines.append(f"- {filename}")
    else:
        lines.append("Downloaded files: None")

    lines.append("")
    lines.append(f"Execution time: {report.execution_time:.1f}s")
    lines.append("")
    lines.append("Result:")
    lines.append("")
    lines.append("PASS" if report.passed else "FAIL")

    if not report.passed and report.failed_stage:
        lines.append("")
        lines.append(f"Failed at stage: {report.failed_stage}")
        if report.failed_error:
            lines.append(f"Error: {report.failed_error}")

    return "\n".join(lines)


class CrawlPipeline:
    """Production discover -> crawl -> download pipeline for one BRF.

    Wires together Discovery, Crawl, Download, Storage, and Metadata
    against persistent storage, so this is safe to run repeatedly for
    manual verification or ad hoc production crawls.
    """

    def __init__(
        self,
        brf_name: str,
        settings: AppSettings | None = None,
        max_depth: int = 2,
        max_pages: int = 20,
        organization_number: str | None = None,
        manual_website_url: str | None = None,
    ) -> None:
        """Initialize the crawl pipeline.

        Args:
            brf_name: Name of the BRF to crawl (e.g. "BRF Solgläntan").
            settings: Application settings (storage/database locations).
            max_depth: Maximum crawl depth.
            max_pages: Maximum pages to crawl.
            organization_number: Known organization number for the BRF, if
                available. Strengthens Discovery scoring and is used as the
                primary key in the verified website registry.
            manual_website_url: A website URL supplied directly by the
                caller (e.g. pasted by a user in the frontend). When set,
                Discovery is skipped entirely and this URL is used as-is.
        """
        self._brf_name = brf_name
        self._settings = settings or AppSettings()
        self._max_depth = max_depth
        self._max_pages = max_pages
        self._organization_number = organization_number
        self._manual_website_url = manual_website_url
        self._report = CrawlReport(brf_name=brf_name)

    @property
    def report(self) -> CrawlReport:
        """Get the current report."""
        return self._report

    async def run(self) -> CrawlReport:
        """Run the complete crawl pipeline.

        Returns:
            CrawlReport with results from all stages.
        """
        start = time.monotonic()

        discovery = DiscoveryEngine(
            providers=[
                SearchEngineDiscovery(),
                SeedUrlDiscovery(seed_urls=[]),
            ],
            strategy="sequential",
            deduplicate=True,
        )
        registry = SqliteVerifiedWebsiteRegistry(database_url=self._settings.database.url)
        crawler: CrawlerEngine | None = None
        download_manager: DownloadManager | None = None

        try:
            await discovery.initialize()
            await registry.initialize()

            self._report.failed_stage = "discovery"
            target = BRF(name=self._brf_name, organization_number=self._organization_number)
            resolver = DiscoveryPipeline(discovery_engine=discovery, registry=registry)
            decision = await resolver.resolve(
                target=target,
                queries=[f"BRF {self._brf_name} årsredovisning"],
                manual_website_url=self._manual_website_url,
            )

            self._report.confidence_band = decision.band.value
            self._report.confidence_score = decision.confidence
            self._report.confidence_explanation = decision.explanation

            if decision.band == ConfidenceBand.LOW:
                # Never crawl a guess: a missing website is an honest gap,
                # a wrong one silently poisons every downstream analyzer.
                raise BRFScraperError(
                    message=(
                        f"Could not confidently identify a website for BRF "
                        f"'{self._brf_name}': {decision.explanation}"
                    ),
                )

            if decision.band == ConfidenceBand.MEDIUM:
                self._report.website_url = decision.website_url
                self._report.discovery_provider = decision.source
                self._report.needs_confirmation = True
                self._report.passed = False
                self._report.failed_error = (
                    "Best-guess website needs user confirmation before crawling."
                )
                return self._report

            if decision.website_url is None:
                # HIGH band always carries a URL (see should_continue_automatically);
                # this only guards against that invariant being violated.
                raise BRFScraperError(
                    message=f"Discovery reported HIGH confidence with no URL for '{self._brf_name}'",
                )

            website_url = decision.website_url
            self._report.website_url = website_url
            self._report.discovery_provider = decision.source

            self._report.failed_stage = "crawl"
            config = CrawlConfig(
                max_depth=self._max_depth,
                max_pages=self._max_pages,
                max_concurrent=3,
                delay_between_requests=0.5,
                respect_robots_txt=True,
                timeout=15.0,
            )
            crawler = CrawlerEngine(config=config)
            await crawler.initialize()

            metrics = await crawler.crawl(
                start_url=website_url,
                max_pages=self._max_pages,
            )
            self._report.pages_crawled = metrics.pages_crawled
            self._report.internal_links = metrics.internal_links
            self._report.external_links = metrics.external_links

            self._report.failed_stage = "find_pdfs"
            pdf_docs = crawler.get_pdf_documents()
            self._report.pdfs_found = len(pdf_docs)

            self._report.failed_stage = "identify_annual_reports"
            annual_reports = [doc for doc in pdf_docs if is_likely_annual_report(doc)]
            self._report.annual_reports_detected = len(annual_reports)

            self._report.failed_stage = "download"
            docs_to_download = annual_reports if annual_reports else pdf_docs

            if docs_to_download:
                storage = LocalStorage(base_dir=self._settings.storage.pdf_dir)
                metadata_repo = SqliteMetadataRepository(
                    database_url=self._settings.database.url,
                )
                downloader = Downloader()

                download_manager = DownloadManager(
                    downloader=downloader,
                    storage=storage,
                    metadata_repo=metadata_repo,
                    max_concurrent=3,
                )
                await download_manager.initialize()

                requests: list[DownloadRequest] = []
                for doc in docs_to_download:
                    try:
                        req = DownloadRequest(
                            source_url=str(doc.source_url),
                            document_url=str(doc.document_url),
                            title=doc.title,
                            filename=doc.filename,
                        )
                        requests.append(req)
                    except Exception as e:
                        logger.warning(
                            "crawl_skip_invalid_doc",
                            url=str(doc.document_url),
                            error=str(e),
                        )
                        self._report.errors += 1

                if requests:
                    results = await download_manager.download_many(requests)

                    for result in results:
                        if result.status == DownloadStatus.COMPLETED:
                            self._report.downloaded += 1
                            if result.document and result.document.original_filename:
                                self._report.downloaded_files.append(
                                    result.document.original_filename
                                )
                        elif result.status == DownloadStatus.DUPLICATE:
                            self._report.duplicates += 1
                        elif result.status == DownloadStatus.FAILED:
                            self._report.errors += 1

            self._report.passed = True

        except Exception as e:
            self._report.passed = False
            if not self._report.failed_stage:
                self._report.failed_stage = "unknown"
            self._report.failed_error = str(e)
            logger.error(
                "crawl_pipeline_failed",
                stage=self._report.failed_stage,
                error=str(e),
            )
        finally:
            self._report.execution_time = time.monotonic() - start
            if download_manager is not None:
                await download_manager.close()
            if crawler is not None:
                await crawler.close()
            await discovery.close()
            await registry.close()

        return self._report
