"""End-to-end smoke test for the BRF scraper pipeline.

Verifies that the existing pipeline components work together:
Discovery → Crawl → Find PDFs → Identify annual reports → Download → Checksums → Metadata.
"""

from __future__ import annotations

import re
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from brf_scraper.crawler.engine import CrawlerEngine
from brf_scraper.crawler.models import CrawlConfig, DocumentReference
from brf_scraper.discovery.engine import DiscoveryEngine
from brf_scraper.discovery.matching import match_brf_by_name
from brf_scraper.discovery.search_engine import SearchEngineDiscovery
from brf_scraper.discovery.seed_urls import SeedUrlDiscovery
from brf_scraper.downloader.downloader import Downloader
from brf_scraper.downloader.manager import DownloadManager
from brf_scraper.downloader.models import DownloadRequest, DownloadStatus
from brf_scraper.downloader.sqlite_metadata import SqliteMetadataRepository
from brf_scraper.exceptions import BRFScraperError
from brf_scraper.storage.local import LocalStorage
from brf_scraper.utils.logging import get_logger

logger = get_logger(__name__)

# Annual report keywords (Swedish + English)
_ANNUAL_REPORT_PATTERNS: list[str] = [
    r"arsredovisning",
    r"årsredovisning",
    r"annual[\s\-_]*report",
    r"års[\s\-_]*redovisning",
]

_YEAR_PATTERN = re.compile(r"20\d{2}")


@dataclass
class SmokeTestReport:
    """Report generated by the smoke test pipeline."""

    brf_name: str
    website_url: str | None = None
    discovery_provider: str | None = None

    pages_crawled: int = 0
    internal_links: int = 0
    external_links: int = 0

    pdfs_found: int = 0
    annual_reports_detected: int = 0
    downloaded: int = 0
    duplicates: int = 0
    errors: int = 0

    downloaded_files: list[str] = field(default_factory=list)

    execution_time: float = 0.0
    passed: bool = False
    failed_stage: str | None = None
    failed_error: str | None = None


def is_likely_annual_report(doc: DocumentReference) -> bool:
    """Determine if a document is likely an annual report.

    Uses URL, filename, and title heuristics only. No PDF parsing.

    Args:
        doc: Document reference from the crawler.

    Returns:
        True if the document is likely an annual report.
    """
    text_parts: list[str] = []

    # Collect text to search
    if doc.filename:
        text_parts.append(doc.filename)
    if doc.title:
        text_parts.append(doc.title)
    text_parts.append(str(doc.document_url))

    text = " ".join(text_parts).lower()

    # Check for annual report keywords
    for pattern in _ANNUAL_REPORT_PATTERNS:
        if re.search(pattern, text):
            return True

    # Check for year pattern in filename — common for annual reports
    # like "rapport-2023.pdf"
    if doc.filename and _YEAR_PATTERN.search(doc.filename):
        return True

    return False


def format_report(report: SmokeTestReport) -> str:
    """Format a SmokeTestReport into the required text output.

    Args:
        report: The smoke test report.

    Returns:
        Formatted report string.
    """
    lines: list[str] = []

    lines.append("=" * 40)
    lines.append("BRF Smoke Test")
    lines.append("=" * 40)
    lines.append("")
    lines.append(f"BRF: {report.brf_name}")
    lines.append(f"Official website: {report.website_url or 'Not found'}")
    lines.append(f"Discovery provider: {report.discovery_provider or 'N/A'}")
    lines.append("")
    lines.append(f"Pages crawled: {report.pages_crawled}")
    lines.append(f"Internal links: {report.internal_links}")
    lines.append(f"External links: {report.external_links}")
    lines.append("")
    lines.append(f"PDFs found: {report.pdfs_found}")
    lines.append(f"Annual reports detected: {report.annual_reports_detected}")
    lines.append(f"Downloaded: {report.downloaded}")
    lines.append(f"Duplicates: {report.duplicates}")
    lines.append(f"Errors: {report.errors}")
    lines.append("")

    if report.downloaded_files:
        lines.append("Downloaded files:")
        lines.append("")
        for filename in report.downloaded_files:
            lines.append(f"- {filename}")
    else:
        lines.append("Downloaded files: None")

    lines.append("")
    lines.append(f"Execution time: {report.execution_time:.1f}s")
    lines.append("")
    lines.append("Result:")
    lines.append("")
    lines.append("PASS" if report.passed else "FAIL")

    if not report.passed and report.failed_stage:
        lines.append("")
        lines.append(f"Failed at stage: {report.failed_stage}")
        if report.failed_error:
            lines.append(f"Error: {report.failed_error}")

    return "\n".join(lines)


class SmokeTest:
    """End-to-end smoke test orchestrator.

    Wires together Discovery, Crawl, Download, Storage, and Metadata
    to verify the complete pipeline works for a given BRF name.
    """

    def __init__(
        self,
        brf_name: str,
        tmp_dir: str | Path | None = None,
        discovery_engine: DiscoveryEngine | None = None,
        crawler_engine: CrawlerEngine | None = None,
        download_manager: DownloadManager | None = None,
    ) -> None:
        """Initialize the smoke test.

        Args:
            brf_name: Name of the BRF to test (e.g. "BRF Solgläntan").
            tmp_dir: Temporary directory for storage/DB. Created if None.
            discovery_engine: Optional injected discovery engine (for testing).
            crawler_engine: Optional injected crawler engine (for testing).
            download_manager: Optional injected download manager (for testing).
        """
        self._brf_name = brf_name
        self._discovery_engine = discovery_engine
        self._crawler_engine = crawler_engine
        self._download_manager = download_manager

        if tmp_dir is not None:
            self._tmp_dir = Path(tmp_dir)
        else:
            import tempfile

            self._tmp_dir = Path(tempfile.mkdtemp(prefix="brf_smoke_"))

        self._report = SmokeTestReport(brf_name=brf_name)
        self._owned_components: list[Any] = []

    @property
    def report(self) -> SmokeTestReport:
        """Get the current report."""
        return self._report

    async def run(self) -> SmokeTestReport:
        """Run the complete smoke test pipeline.

        Returns:
            SmokeTestReport with results from all stages.
        """
        start = time.monotonic()

        try:
            await self._stage_discover()
            await self._stage_crawl()
            self._stage_find_pdfs()
            self._stage_identify_annual_reports()
            await self._stage_download()
            self._stage_verify_checksums()
            self._report.passed = True
        except Exception as e:
            self._report.passed = False
            if not self._report.failed_stage:
                self._report.failed_stage = "unknown"
            self._report.failed_error = str(e)
            logger.error(
                "smoke_test_failed",
                stage=self._report.failed_stage,
                error=str(e),
            )
        finally:
            self._report.execution_time = time.monotonic() - start
            await self._cleanup()

        return self._report

    async def _stage_discover(self) -> None:
        """Stage 1: Discover the official BRF website."""
        self._report.failed_stage = "discovery"

        engine = self._discovery_engine
        if engine is None:
            engine = DiscoveryEngine(
                providers=[
                    SearchEngineDiscovery(),
                    SeedUrlDiscovery(seed_urls=[]),
                ],
                strategy="sequential",
                deduplicate=True,
            )
            self._owned_components.append(("discovery", engine))

        await engine.initialize()

        result = await engine.discover(
            queries=[f"BRF {self._brf_name} årsredovisning"],
        )

        # Find best matching BRF by name
        best = match_brf_by_name(self._brf_name, result.brfs)
        if best is None:
            raise BRFScraperError(
                message=f"Could not find website for BRF '{self._brf_name}'",
            )

        self._report.website_url = str(best.website_url)
        self._report.discovery_provider = best.source.value

        logger.info(
            "smoke_test_discovery_complete",
            url=self._report.website_url,
            provider=self._report.discovery_provider,
        )

    async def _stage_crawl(self) -> None:
        """Stage 2: Crawl the BRF website."""
        self._report.failed_stage = "crawl"

        if not self._report.website_url:
            raise BRFScraperError(message="No website URL to crawl")

        engine = self._crawler_engine
        if engine is None:
            config = CrawlConfig(
                max_depth=2,
                max_pages=20,
                max_concurrent=3,
                delay_between_requests=0.5,
                respect_robots_txt=True,
                timeout=15.0,
            )
            engine = CrawlerEngine(config=config)
            self._owned_components.append(("crawler", engine))

        await engine.initialize()

        metrics = await engine.crawl(
            start_url=self._report.website_url,
            max_pages=20,
        )

        self._report.pages_crawled = metrics.pages_crawled
        self._report.internal_links = metrics.internal_links
        self._report.external_links = metrics.external_links

        # Store crawl results for later stages
        self._crawl_engine = engine

        logger.info(
            "smoke_test_crawl_complete",
            pages=self._report.pages_crawled,
            pdfs=metrics.pdfs_found,
        )

    def _stage_find_pdfs(self) -> None:
        """Stage 3: Find all PDF documents from the crawl."""
        self._report.failed_stage = "find_pdfs"

        engine = self._crawl_engine
        assert engine is not None

        self._pdf_docs = engine.get_pdf_documents()
        self._report.pdfs_found = len(self._pdf_docs)

        logger.info("smoke_test_pdfs_found", count=self._report.pdfs_found)

    def _stage_identify_annual_reports(self) -> None:
        """Stage 4: Identify likely annual reports from PDFs."""
        self._report.failed_stage = "identify_annual_reports"

        self._annual_reports = [doc for doc in self._pdf_docs if is_likely_annual_report(doc)]
        self._report.annual_reports_detected = len(self._annual_reports)

        logger.info(
            "smoke_test_annual_reports_detected",
            count=self._report.annual_reports_detected,
        )

    async def _stage_download(self) -> None:
        """Stage 5-7: Download, verify checksums, store metadata."""
        self._report.failed_stage = "download"

        docs_to_download = self._annual_reports if self._annual_reports else self._pdf_docs
        if not docs_to_download:
            logger.info("smoke_test_no_documents_to_download")
            return

        manager = self._download_manager
        if manager is None:
            storage_dir = self._tmp_dir / "docs"
            db_path = self._tmp_dir / "metadata.db"

            storage = LocalStorage(base_dir=storage_dir)
            metadata_repo = SqliteMetadataRepository(
                database_url=f"sqlite+aiosqlite:///{db_path}",
            )
            downloader = Downloader()

            manager = DownloadManager(
                downloader=downloader,
                storage=storage,
                metadata_repo=metadata_repo,
                max_concurrent=3,
            )
            self._owned_components.append(("download_manager", manager))

        await manager.initialize()

        # Convert DocumentReference -> DownloadRequest
        requests: list[DownloadRequest] = []
        for doc in docs_to_download:
            try:
                req = DownloadRequest(
                    source_url=str(doc.source_url),
                    document_url=str(doc.document_url),
                    title=doc.title,
                    filename=doc.filename,
                )
                requests.append(req)
            except Exception as e:
                logger.warning(
                    "smoke_test_skip_invalid_doc",
                    url=str(doc.document_url),
                    error=str(e),
                )
                self._report.errors += 1

        if not requests:
            return

        results = await manager.download_many(requests)

        # Tally results
        for result in results:
            if result.status == DownloadStatus.COMPLETED:
                self._report.downloaded += 1
                if result.document and result.document.original_filename:
                    self._report.downloaded_files.append(result.document.original_filename)
            elif result.status == DownloadStatus.DUPLICATE:
                self._report.duplicates += 1
            elif result.status == DownloadStatus.FAILED:
                self._report.errors += 1

        self._download_manager = manager

        logger.info(
            "smoke_test_download_complete",
            downloaded=self._report.downloaded,
            duplicates=self._report.duplicates,
            errors=self._report.errors,
        )

    def _stage_verify_checksums(self) -> None:
        """Stage 6: Verify that all downloaded documents have checksums.

        Checksum computation and duplicate detection are handled by
        DownloadManager. This stage just validates the results.
        """
        self._report.failed_stage = "verify_checksums"

        manager = self._download_manager
        if manager is None:
            return

        for result in manager.results:
            if result.status == DownloadStatus.COMPLETED and result.document:
                checksum = result.document.sha256_checksum
                if not checksum or len(checksum) != 64:
                    logger.warning(
                        "smoke_test_invalid_checksum",
                        document_id=str(result.document.id),
                    )
                    self._report.errors += 1

    async def _cleanup(self) -> None:
        """Clean up owned components in reverse order."""
        for name, component in reversed(self._owned_components):
            try:
                await component.close()
            except Exception:
                logger.debug("smoke_test_cleanup_error", component=name)
        self._owned_components.clear()
