-- Besiktningshjälp (Inspection Assistant): one inspection per (user, property),
-- reusable across the "before / during / after" workflow (PART 10). Follows
-- the same pattern as analysis_requests/saved_properties: personal ownership
-- rows cascade from auth.users, but never cascade-delete the shared
-- property/analysis rows underneath them.
create table if not exists public.inspections (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  property_id uuid not null references public.properties (id),
  analysis_id uuid references public.analyses (id),
  step smallint not null default 1, -- 1 = before, 2 = during, 3 = after
  status text not null default 'before' check (status in ('before', 'during', 'after', 'complete')),
  prep_checklist jsonb not null default '{}'::jsonb, -- { [prepStepId]: boolean }
  checklist jsonb not null default '{}'::jsonb, -- { [roomId]: { [checkpointId]: { checked, severity, notes, photoIds } } }
  observations jsonb not null default '[]'::jsonb, -- [{ id, text, createdAt }]
  summary jsonb, -- generated after-inspection summary, cached
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, property_id)
);

create index if not exists inspections_user_id_idx on public.inspections (user_id);
create index if not exists inspections_property_id_idx on public.inspections (property_id);

alter table public.inspections enable row level security;

create policy "Inspections are viewable by owner"
  on public.inspections for select
  using (auth.uid() = user_id);

grant select, insert, update, delete on public.inspections to service_role;

create table if not exists public.inspection_documents (
  id uuid primary key default gen_random_uuid(),
  inspection_id uuid not null references public.inspections (id) on delete cascade,
  doc_type text not null check (doc_type in (
    'annual_report', 'inspection_report', 'energy_declaration', 'floor_plan',
    'maintenance_plan', 'bylaws', 'other'
  )),
  storage_path text not null,
  original_filename text,
  content_type text,
  uploaded_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists inspection_documents_inspection_id_idx
  on public.inspection_documents (inspection_id);

alter table public.inspection_documents enable row level security;

create policy "Inspection documents are viewable by owner"
  on public.inspection_documents for select
  using (
    exists (
      select 1 from public.inspections i
      where i.id = inspection_id and i.user_id = auth.uid()
    )
  );

grant select, insert, delete on public.inspection_documents to service_role;

create table if not exists public.inspection_photos (
  id uuid primary key default gen_random_uuid(),
  inspection_id uuid not null references public.inspections (id) on delete cascade,
  room text not null,
  checkpoint_id text,
  storage_path text not null,
  original_filename text,
  created_at timestamptz not null default now()
);

create index if not exists inspection_photos_inspection_id_idx
  on public.inspection_photos (inspection_id);

alter table public.inspection_photos enable row level security;

create policy "Inspection photos are viewable by owner"
  on public.inspection_photos for select
  using (
    exists (
      select 1 from public.inspections i
      where i.id = inspection_id and i.user_id = auth.uid()
    )
  );

grant select, insert, delete on public.inspection_photos to service_role;

-- Storage bucket for inspection documents & photos (private; served only
-- through signed URLs generated by the API routes, same as brf-annual-reports).
insert into storage.buckets (id, name, public)
values ('inspection-files', 'inspection-files', false)
on conflict (id) do nothing;
