-- The public map (/karta): sale listings, buyer wishes and home exchanges that signed-in users post, and the
-- built-in example pins. Until now the map kept visitors' pins in their own browser.
--
-- Access: row level security is on and there is no policy, so the public and signed-in users can read and write
-- nothing directly. Everything goes through the site's own API (the service role), which returns only what the map
-- shows - never owner_id - and checks who may change what. The API's rules (limits, links, places in Sweden) are
-- repeated here as checks, so a bug in the API cannot store a row the map could not draw.
--
-- transport: the lite area analysis of a SALE listing - the nearest bus stop and train station, from Transitous (open
-- data of Trafiklab and others). Generated by the server right after the listing is saved, or the first time someone
-- opens it if that failed. transport_status: none (not tried), pending (being fetched), ready, unavailable (the
-- source could not be reached; tried again later).
--
-- Safe to run more than once.

create table if not exists public.map_listings (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('sale', 'buyer', 'exchange')),
  -- who posted it; null for the built-in examples. A deleted account takes its pins with it.
  owner_id uuid references auth.users(id) on delete cascade,
  -- 'sale-1', 'buyer-101', 'exchange-201'...: the built-in examples, whose words come from the site's message files
  example_key text unique,
  title text not null default '' check (char_length(title) <= 120),
  -- the place: an address or an area (for an exchange, the home that is offered)
  note text not null default '' check (char_length(note) <= 300),
  details text check (char_length(details) <= 2000),
  meta text check (char_length(meta) <= 200),
  link text check (link is null or (char_length(link) <= 500 and link ~* '^https?://')),
  -- a picture: a path in the bucket map-listing-images ("<owner id>/<name>.webp") or, for the examples, an https address
  image text check (image is null or (char_length(image) <= 500 and (image ~ '^https://' or image ~ '^[0-9a-f-]{36}/[A-Za-z0-9_-]+\.webp$'))),
  lat double precision not null check (lat between 54.5 and 69.5),
  lng double precision not null check (lng between 10 and 25),
  -- an exchange: the place the owner wants to move to
  to_note text check (to_note is null or char_length(to_note) <= 300),
  to_lat double precision check (to_lat is null or to_lat between 54.5 and 69.5),
  to_lng double precision check (to_lng is null or to_lng between 10 and 25),
  -- the team can hide a pin; the owner still sees their own
  status text not null default 'published' check (status in ('published', 'hidden')),
  hidden_reason text check (hidden_reason is null or char_length(hidden_reason) <= 300),
  hidden_by uuid references auth.users(id) on delete set null,
  hidden_at timestamptz,
  transport jsonb,
  transport_status text not null default 'none' check (transport_status in ('none', 'pending', 'ready', 'unavailable')),
  transport_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (owner_id is not null or example_key is not null),
  check (kind <> 'exchange' or (to_lat is not null and to_lng is not null)),
  check (kind = 'exchange' or (to_lat is null and to_lng is null and to_note is null)),
  check (kind = 'sale' or transport is null)
);

create index if not exists map_listings_status_kind_idx on public.map_listings (status, kind);
create index if not exists map_listings_owner_idx on public.map_listings (owner_id, created_at desc);

-- updated_at follows every change (public.set_updated_at() is defined in an earlier migration).
drop trigger if exists map_listings_set_updated_at on public.map_listings;
create trigger map_listings_set_updated_at
  before update on public.map_listings
  for each row execute function public.set_updated_at();

alter table public.map_listings enable row level security;
revoke all on public.map_listings from anon, authenticated;
grant select, insert, update, delete on public.map_listings to service_role;

-- Pictures: public read by address, at most 2 MB, WebP only (the server decodes every upload, drops its metadata,
-- including any GPS position, and re-encodes it to WebP before storing it). Written only by the server.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('map-listing-images', 'map-listing-images', true, 2097152, array['image/webp'])
on conflict (id) do nothing;

-- The built-in examples (the pins the map has always shown). Their texts are in the message files, by example_key.
insert into public.map_listings (kind, example_key, title, image, link, lat, lng, to_lat, to_lng)
values
  ('sale', 'sale-1', 'Kanalgatan 41C', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 55.83626936841034, 13.301669377943158, null, null),
  ('sale', 'sale-2', 'Hörngatan 11', 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 58.27749450906411, 12.285267106116207, null, null),
  ('sale', 'sale-3', 'Timmermansgatan 22', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.3151, 18.071, null, null),
  ('sale', 'sale-4', 'Sveavägen 98', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.3428, 18.0448, null, null),
  ('sale', 'sale-5', 'Strandvägen 7', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.3358, 18.0894, null, null),
  ('sale', 'sale-6', 'Fleminggatan 45', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.3325, 18.0326, null, null),
  ('sale', 'sale-7', 'Västerlånggatan 15', 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.3251, 18.0711, null, null),
  ('sale', 'sale-8', 'Ulvsundavägen 106', 'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.34, 17.9294, null, null),
  ('sale', 'sale-9', 'Råsundavägen 12', 'https://images.unsplash.com/photo-1512915922686-57c11dde9b6b?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.3601, 17.9956, null, null),
  ('sale', 'sale-10', 'Sicklastråket 3', 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.3053, 18.1109, null, null),
  ('sale', 'sale-11', 'Täby Torg 5', 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.4439, 18.0687, null, null),
  ('sale', 'sale-12', 'Larsviksvägen 9', 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.3656, 18.1353, null, null),
  ('sale', 'sale-13', 'Enskedevägen 88', 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.2809, 18.081, null, null),
  ('sale', 'sale-14', 'Maltesholmsvägen 41', 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.3623, 17.8371, null, null),
  ('sale', 'sale-15', 'Årsta Torg 6', 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=900&q=80', 'https://www.hemnet.se/', 59.2934, 18.0553, null, null),
  ('buyer', 'buyer-101', '', null, null, 59.312612847910174, 18.06196320281545, null, null),
  ('buyer', 'buyer-102', '', null, null, 59.40263434990332, 17.943175200850128, null, null),
  ('buyer', 'buyer-103', '', null, null, 59.3448, 18.048, null, null),
  ('buyer', 'buyer-104', '', null, null, 59.3372, 18.092, null, null),
  ('buyer', 'buyer-105', '', null, null, 59.304, 17.972, null, null),
  ('buyer', 'buyer-106', '', null, null, 59.343, 17.926, null, null),
  ('buyer', 'buyer-107', '', null, null, 59.359, 18, null, null),
  ('buyer', 'buyer-108', '', null, null, 59.3095, 18.158, null, null),
  ('buyer', 'buyer-109', '', null, null, 59.447, 18.07, null, null),
  ('buyer', 'buyer-110', '', null, null, 59.3105, 18.019, null, null),
  ('buyer', 'buyer-111', '', null, null, 59.2915, 18.061, null, null),
  ('buyer', 'buyer-112', '', null, null, 59.2845, 18.078, null, null),
  ('buyer', 'buyer-113', '', null, null, 59.3615, 17.97, null, null),
  ('buyer', 'buyer-114', '', null, null, 59.402, 18.04, null, null),
  ('buyer', 'buyer-115', '', null, null, 59.858, 17.635, null, null),
  ('exchange', 'exchange-201', '', null, null, 59.3151, 18.071, 59.3325, 18.0326),
  ('exchange', 'exchange-202', '', null, null, 59.34, 17.9294, 59.8586, 17.6389),
  ('exchange', 'exchange-203', '', null, null, 59.345, 18.05, 59.307, 18.014),
  ('exchange', 'exchange-204', '', null, null, 59.338, 18.085, 59.345, 17.935),
  ('exchange', 'exchange-205', '', null, null, 59.33, 18.028, 59.308, 18.16),
  ('exchange', 'exchange-206', '', null, null, 59.303, 17.97, 59.44, 18.065),
  ('exchange', 'exchange-207', '', null, null, 59.295, 18.05, 59.318, 18.065),
  ('exchange', 'exchange-208', '', null, null, 59.362, 17.99, 59.363, 17.968),
  ('exchange', 'exchange-209', '', null, null, 59.2478, 18.0972, 59.283, 18.085),
  ('exchange', 'exchange-210', '', null, null, 59.2701, 18.1183, 59.3617, 17.8697),
  ('exchange', 'exchange-211', '', null, null, 59.4014, 18.0378, 59.3956, 18.0817),
  ('exchange', 'exchange-212', '', null, null, 59.32, 18.075, 57.7072, 11.9668),
  ('exchange', 'exchange-213', '', null, null, 59.347, 18.04, 55.605, 13.0038),
  ('exchange', 'exchange-214', '', null, null, 59.335, 18.035, 59.6099, 16.5448),
  ('exchange', 'exchange-215', '', null, null, 59.8586, 17.6389, 59.331, 18.03)
on conflict (example_key) do nothing;
