-- Documents auto-discovered on a listing broker's own website (via the
-- Hemnet "Läs mer hos mäklaren" link) during the background analysis
-- pipeline — annual reports, bylaws, energy declarations, inspection
-- protocols. Distinct from inspection_documents (user-driven manual
-- uploads, scoped to one user's Premium inspection session): this table is
-- scoped to the property/analysis itself and populated automatically, with
-- no inspection_id to attach to at discovery time.
create table if not exists public.broker_documents (
  id uuid primary key default gen_random_uuid(),
  property_id uuid not null references public.properties (id),
  doc_type text not null check (doc_type in (
    'annual_report', 'inspection_report', 'energy_declaration',
    'bylaws', 'floor_plan', 'other'
  )),
  storage_path text not null,
  original_filename text,
  content_type text,
  content_hash text not null,
  -- Provenance: where on the broker's site this was found.
  source_url text not null,
  broker_url text,
  discovered_at timestamptz not null default now(),
  -- Only populated for doc_type = 'inspection_report' — AI-derived findings,
  -- shape matches extractor/inspection_extractor.py's InspectionExtractionResult.
  ai_findings jsonb,
  ai_model text,
  -- Only populated for doc_type = 'annual_report' — points at the canonical,
  -- cross-property-deduplicated row in brf_annual_reports rather than
  -- duplicating the PDF bytes/extraction a second time.
  brf_annual_report_id uuid references public.brf_annual_reports (id),
  unique (property_id, content_hash)
);

create index if not exists broker_documents_property_id_idx
  on public.broker_documents (property_id);

create index if not exists broker_documents_doc_type_idx
  on public.broker_documents (doc_type);

alter table public.broker_documents enable row level security;

-- RLS enabled with NO policies on purpose, same pattern as
-- brf_annual_reports: this table is populated by the background analysis
-- pipeline (service role), not by a direct authenticated user action, and
-- surfaced through the report page via signed URLs generated server-side.
grant select, insert, update on public.broker_documents to service_role;

-- Storage bucket for broker-discovered documents (private; served only
-- through signed URLs generated by the API routes, same as inspection-files).
insert into storage.buckets (id, name, public)
values ('broker-documents', 'broker-documents', false)
on conflict (id) do nothing;
